version: '3'
services:
  # MySQL 8
  mysql:
    image: mysql
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: 123456
    ports:
      - "3306:3306"
    networks:
      - hzd-network
#      - bridge
    volumes:
      - mysql-data:/var/lib/mysql
      - ./mysql-init:/docker-entrypoint-initdb.d # 自动执行启动脚本

  # Redis 6
  redis:
    image: redis
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - hzd-network
#      - bridge

  # RabbitMQ 3.12.6
#  rabbitmq:
#    image: rabbitmq:3.12.6-management
#    container_name: rabbitmq
#    environment:
#      RABBITMQ_DEFAULT_USER: guest
#      RABBITMQ_DEFAULT_PASS: guest
#    ports:
#      - "5672:5672"
#      - "15672:15672" # Management UI
#    networks:
#      - hzd-network

  # Nacos 2.2.0
  nacos:
    image: nacos/nacos-server
    container_name: nacos
    environment:
      MODE: standalone
    ports:
      - "8848:8848"
    networks:
      - hzd-network
#      - bridge

# Network Configuration
networks:
  hzd-network:
    driver: bridge

# Volumes Configuration
volumes:
  mysql-data:
    driver: local
