version: '2'
services:
  # MySQL 8
  mysql:
    image: mysql
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: 123456
    ports:
      - "3306:3306"
    networks:
      - hzd-network
    volumes:
      - mysql-data:/var/lib/mysql
      - ./mysql-init:/docker-entrypoint-initdb.d # 自动执行初始化sql脚本

  # Redis 6
  redis:
    image: redis
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - hzd-network

  # Nacos 2.2.0
  nacos:
    image: nacos/nacos-server
    container_name: nacos
    environment:
      MODE: standalone
    ports:
      - "8848:8848"
    networks:
      - hzd-network

  nginx:
    image: nginx
    container_name: nginx
    volumes:
      - ./nginx.conf:/code/logistics-system/nginx/nginx.conf
      - ./frontend/dist:/code/logistics-system/logisticsManager-frontend/dist  # 将前端的 dist 文件挂载到 Nginx 服务器
    ports:
      - "80:80"  # 映射容器的 80 端口到主机的 80 端口
    networks:
      - hzd-network

# Network Configuration
networks:
  hzd-network:
    driver: bridge


# Volumes Configuration
volumes:
  mysql-data:
    driver: local
