server:
  port: 9084

spring:
  application:
    name: report-service
  config:
    import: nacos:report-service-dev.yml
  cloud:
    nacos:
      discovery:
        server-addr: nacos:8848
      config:
        server-addr: nacos:8848
        file-extension: yml
      loadbalancer:
        enabled: true
  datasource:
    url: jdbc:mysql://mysql:3306/reportdb
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  data:
    redis:
      host: redis
      port: 6379

#  rabbitmq:
#    host: localhost
#    port: 5672
#    username: guest
#    password: guest
#    listener:
#      simple:
#        retry:
#          enabled: true
#          max-attempts: 3
#    queues:
#      order-statistics: order.statistics.queue

#  task:
#    scheduling:
#      pool:
#        size: 5

#springdoc:
#  api-docs:
#    enabled: true
#    path: /v3/api-docs
#  swagger-ui:
#    path: /swagger-ui.html
#    enabled: true
#  packages-to-scan: com.maxrayyy.reportservice.controller
#  default-produces-media-type: application/json
#  default-consumes-media-type: application/json
#  paths-to-match: /api/**

report:
  file:
    path: files/reports # 导出文件的存储路径
