spring:

  application:
    name: transport-service

  config:
    import: nacos:transport-service-dev.yml

  cloud:
    nacos:
      discovery:
        server-addr: 100.80.148.238:8848
      config:
        server-addr: 100.80.148.238:8848
        file-extension: yml

  datasource:
    url: jdbc:mysql://localhost:3306/transport_management?serverTimezone=UTC
    username: root
    password: zztxjy620
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
        dialect: org.hibernate.dialect.MySQL8Dialect
