spring:
  application:
    name: transport-service
  config:
    import: nacos:transport-service-dev.yml
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
      config:
        server-addr: localhost:8848
        file-extension: yml
