spring:
  datasource:
    url: jdbc:mysql://mysql:3306/storagedb?serverTimezone=UTC
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  application:
    name: storage-service
  config:
    import: nacos:storage-service-dev.yml
  cloud:
    nacos:
      discovery:
        server-addr: nacos:8848
      config:
        server-addr: nacos:8848
        file-extension: yml
server:
  address: 0.0.0.0
